[theme]
primaryColor="#FFA000" # primary900
backgroundColor="#FFFFFF" # 白
secondaryBackgroundColor="#E2F1FF" # secondary100
textColor="#212121" # neutrals900
font="sans serif"

[server]
headless = true
port = 8501
